---

- name: IOS command execution
  hosts: switch
  gather_facts: false
  connection: local

  tasks:
    - name: getting interface
      ios_command:
        commands:
          - show version

      register: result

    -  debug: var=result.stdout_lines

    - name: saving interface details in files
      copy: content="{{ result.stdout[0] }}" dest="./output/{{ inventory_hostname }}_interface.txt"
